package Calculator;


/**
* Calculator/ClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Monday, April 2, 2018 2:56:55 PM CEST
*/

public interface ClientOperations 
{
  String callback (String result, int request_id);
} // interface ClientOperations
