package Calculator;

/**
* Calculator/ClientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Monday, April 2, 2018 2:56:55 PM CEST
*/

public final class ClientHolder implements org.omg.CORBA.portable.Streamable
{
  public Calculator.Client value = null;

  public ClientHolder ()
  {
  }

  public ClientHolder (Calculator.Client initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Calculator.ClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Calculator.ClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Calculator.ClientHelper.type ();
  }

}
