package Calculator;


/**
* Calculator/Request.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Monday, April 2, 2018 2:56:55 PM CEST
*/

public final class Request implements org.omg.CORBA.portable.IDLEntity
{
  public String request_object_name = null;
  public String interface_request_name = null;
  public String operation_name = null;
  public String result = null;
  public int request_number = (int)0;
  public org.omg.CORBA.Any operation_params[] = null;

  public Request ()
  {
  } // ctor

  public Request (String _request_object_name, String _interface_request_name, String _operation_name, String _result, int _request_number, org.omg.CORBA.Any[] _operation_params)
  {
    request_object_name = _request_object_name;
    interface_request_name = _interface_request_name;
    operation_name = _operation_name;
    result = _result;
    request_number = _request_number;
    operation_params = _operation_params;
  } // ctor

} // class Request
