package Calculator;

/**
* Calculator/RequestHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Monday, April 2, 2018 2:56:55 PM CEST
*/

public final class RequestHolder implements org.omg.CORBA.portable.Streamable
{
  public Calculator.Request value = null;

  public RequestHolder ()
  {
  }

  public RequestHolder (Calculator.Request initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Calculator.RequestHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Calculator.RequestHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Calculator.RequestHelper.type ();
  }

}
