package Calculator;


/**
* Calculator/SchedulerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Monday, April 2, 2018 2:56:55 PM CEST
*/

abstract public class SchedulerHelper
{
  private static String  _id = "IDL:Calculator/Scheduler:1.0";

  public static void insert (org.omg.CORBA.Any a, Calculator.Scheduler that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Calculator.Scheduler extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Calculator.SchedulerHelper.id (), "Scheduler");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Calculator.Scheduler read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_SchedulerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Calculator.Scheduler value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Calculator.Scheduler narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Calculator.Scheduler)
      return (Calculator.Scheduler)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Calculator._SchedulerStub stub = new Calculator._SchedulerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Calculator.Scheduler unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Calculator.Scheduler)
      return (Calculator.Scheduler)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Calculator._SchedulerStub stub = new Calculator._SchedulerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
