package Calculator;

/**
* Calculator/SchedulerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Monday, April 2, 2018 2:56:55 PM CEST
*/

public final class SchedulerHolder implements org.omg.CORBA.portable.Streamable
{
  public Calculator.Scheduler value = null;

  public SchedulerHolder ()
  {
  }

  public SchedulerHolder (Calculator.Scheduler initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Calculator.SchedulerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Calculator.SchedulerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Calculator.SchedulerHelper.type ();
  }

}
