package Calculator;


/**
* Calculator/SchedulerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Monday, April 2, 2018 2:56:55 PM CEST
*/

public interface SchedulerOperations 
{
  boolean post (Calculator.Request req, int num_client);
  void del (int request_id, int num_client);
  boolean check_req (Calculator.Request req) throws Calculator.Invalid_req;
} // interface SchedulerOperations
