package Calculator;


/**
* Calculator/SchedulerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Monday, April 2, 2018 2:56:55 PM CEST
*/

public abstract class SchedulerPOA extends org.omg.PortableServer.Servant
 implements Calculator.SchedulerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("post", new java.lang.Integer (0));
    _methods.put ("del", new java.lang.Integer (1));
    _methods.put ("check_req", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Calculator/Scheduler/post
       {
         Calculator.Request req = Calculator.RequestHelper.read (in);
         int num_client = in.read_long ();
         boolean $result = false;
         $result = this.post (req, num_client);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Calculator/Scheduler/del
       {
         int request_id = in.read_long ();
         int num_client = in.read_long ();
         this.del (request_id, num_client);
         out = $rh.createReply();
         break;
       }

       case 2:  // Calculator/Scheduler/check_req
       {
         try {
           Calculator.Request req = Calculator.RequestHelper.read (in);
           boolean $result = false;
           $result = this.check_req (req);
           out = $rh.createReply();
           out.write_boolean ($result);
         } catch (Calculator.Invalid_req $ex) {
           out = $rh.createExceptionReply ();
           Calculator.Invalid_reqHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Calculator/Scheduler:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Scheduler _this() 
  {
    return SchedulerHelper.narrow(
    super._this_object());
  }

  public Scheduler _this(org.omg.CORBA.ORB orb) 
  {
    return SchedulerHelper.narrow(
    super._this_object(orb));
  }


} // class SchedulerPOA
