package scheduler;


/**
* scheduler/Request.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from treatment_scheduler.idl
* Friday, March 23, 2018 7:22:16 PM CET
*/

public final class Request implements org.omg.CORBA.portable.IDLEntity
{
  public String object_req_name = null;
  public String interface_req_name = null;
  public String op_req = null;
  public org.omg.CORBA.Any req_params[] = null;

  public Request ()
  {
  } // ctor

  public Request (String _object_req_name, String _interface_req_name, String _op_req, org.omg.CORBA.Any[] _req_params)
  {
    object_req_name = _object_req_name;
    interface_req_name = _interface_req_name;
    op_req = _op_req;
    req_params = _req_params;
  } // ctor

} // class Request
