package scheduler;

/**
* scheduler/RequestHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from treatment_scheduler.idl
* Friday, March 23, 2018 7:22:16 PM CET
*/

public final class RequestHolder implements org.omg.CORBA.portable.Streamable
{
  public scheduler.Request value = null;

  public RequestHolder ()
  {
  }

  public RequestHolder (scheduler.Request initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scheduler.RequestHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scheduler.RequestHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scheduler.RequestHelper.type ();
  }

}
