package scheduler;

/**
* scheduler/SchedulerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from treatment_scheduler.idl
* Friday, March 23, 2018 7:22:16 PM CET
*/

public final class SchedulerHolder implements org.omg.CORBA.portable.Streamable
{
  public scheduler.Scheduler value = null;

  public SchedulerHolder ()
  {
  }

  public SchedulerHolder (scheduler.Scheduler initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scheduler.SchedulerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scheduler.SchedulerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scheduler.SchedulerHelper.type ();
  }

}
