package scheduler;


/**
* scheduler/SchedulerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from treatment_scheduler.idl
* Friday, March 23, 2018 7:22:16 PM CET
*/

public interface SchedulerOperations 
{
  scheduler.Request get (short index);
  boolean post (scheduler.Request req);
  void del (short index);
  boolean check_req (scheduler.Request req) throws scheduler.invalid_req;
} // interface SchedulerOperations
